version: "3.3"

services:
  signaling:
    image: yoonyounghun/signaling:latest
    container_name: signaling
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      CLIENT_ORIGINS: "https://iamyounghun.site,http://localhost:3000"

  coturn:
    image: coturn/coturn:latest
    container_name: coturn
    restart: unless-stopped
    network_mode: host
    command: >
      -n
      --log-file=stdout
      --lt-cred-mech
      --fingerprint
      --realm=iamyounghun.site
      --server-name=iamyounghun.site
      --user=iddyoon:iddyoon
      --external-ip=8.229.223.216
      --listening-port=3478
      --min-port=49160
      --max-port=49200
