import type { Metadata } from "next";
import "./globals.css";
import { inter } from "./utils/style/fonts";

export const metadata: Metadata = {
  title: "Web Tutorials",
  description: "Generated by Young-Heon",
};

export default function RootLayout({children}:{children: React.ReactNode;}){
  return (
    <html lang="en">
      <body className={`${inter.className}, bg-slate-100 p-5`}>
        {children}
      </body>
    </html>
  );
}
